const Blog = require('./models/blog');

const blogs = [
  {
    title: 'Blog Title 1',
    img:
      'https://images.unsplash.com/photo-1601814933824-fd0b574dd592?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8c3RhciUyMHdhcnN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam etiam erat velit scelerisque. Praesent tristique magna sit amet purus gravida quis blandit. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Non odio euismod lacinia at quis. Mauris pellentesque pulvinar pellentesque habitant. Viverra accumsan in nisl nisi scelerisque. Risus feugiat in ante metus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum lacinia quis vel eros donec ac odio tempor.

      Sed elementum tempus egestas sed sed risus. Varius vel pharetra vel turpis nunc eget lorem. Diam vulputate ut pharetra sit amet. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Facilisis volutpat est velit egestas dui. Est ultricies integer quis auctor elit sed. Lacus sed viverra tellus in hac. Non blandit massa enim nec dui nunc mattis. Dolor sed viverra ipsum nunc. Fringilla urna porttitor rhoncus dolor purus. Vitae tempus quam pellentesque nec nam aliquam sem. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Duis convallis convallis tellus id interdum velit laoreet id donec. Mi bibendum neque egestas congue quisque egestas. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Aliquam ut porttitor leo a diam sollicitudin. Dui faucibus in ornare quam viverra orci sagittis.
      
      Nec ullamcorper sit amet risus nullam eget. Tortor consequat id porta nibh venenatis cras sed felis eget. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Consequat semper viverra nam libero justo laoreet. Augue eget arcu dictum varius duis. Tortor posuere ac ut consequat semper. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Condimentum lacinia quis vel eros donec ac odio tempor. Id diam vel quam elementum pulvinar etiam non quam.
      
      Nec ullamcorper sit amet risus. Enim lobortis scelerisque fermentum dui faucibus in ornare. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Sed nisi lacus sed viverra tellus in hac. Cras pulvinar mattis nunc sed. In hendrerit gravida rutrum quisque. Vulputate odio ut enim blandit volutpat maecenas. Sed odio morbi quis commodo. Tellus cras adipiscing enim eu turpis egestas. Dui faucibus in ornare quam viverra orci sagittis eu. Vivamus at augue eget arcu dictum. Magna fringilla urna porttitor rhoncus. Sollicitudin nibh sit amet commodo nulla facilisi.
      
      Vitae justo eget magna fermentum iaculis eu non diam. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Scelerisque eu ultrices vitae auctor eu augue ut lectus. In mollis nunc sed id semper risus in. Vitae sapien pellentesque habitant morbi. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. At risus viverra adipiscing at in tellus integer feugiat. Nibh tellus molestie nunc non blandit massa.`,
    author: 'Jon Doe',
  },
  {
    title: 'Blog Title 2',
    img:
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8ZWFydGh8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam etiam erat velit scelerisque. Praesent tristique magna sit amet purus gravida quis blandit. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Non odio euismod lacinia at quis. Mauris pellentesque pulvinar pellentesque habitant. Viverra accumsan in nisl nisi scelerisque. Risus feugiat in ante metus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum lacinia quis vel eros donec ac odio tempor.

      Sed elementum tempus egestas sed sed risus. Varius vel pharetra vel turpis nunc eget lorem. Diam vulputate ut pharetra sit amet. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Facilisis volutpat est velit egestas dui. Est ultricies integer quis auctor elit sed. Lacus sed viverra tellus in hac. Non blandit massa enim nec dui nunc mattis. Dolor sed viverra ipsum nunc. Fringilla urna porttitor rhoncus dolor purus. Vitae tempus quam pellentesque nec nam aliquam sem. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Duis convallis convallis tellus id interdum velit laoreet id donec. Mi bibendum neque egestas congue quisque egestas. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Aliquam ut porttitor leo a diam sollicitudin. Dui faucibus in ornare quam viverra orci sagittis.
      
      Nec ullamcorper sit amet risus nullam eget. Tortor consequat id porta nibh venenatis cras sed felis eget. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Consequat semper viverra nam libero justo laoreet. Augue eget arcu dictum varius duis. Tortor posuere ac ut consequat semper. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Condimentum lacinia quis vel eros donec ac odio tempor. Id diam vel quam elementum pulvinar etiam non quam.
      
      Nec ullamcorper sit amet risus. Enim lobortis scelerisque fermentum dui faucibus in ornare. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Sed nisi lacus sed viverra tellus in hac. Cras pulvinar mattis nunc sed. In hendrerit gravida rutrum quisque. Vulputate odio ut enim blandit volutpat maecenas. Sed odio morbi quis commodo. Tellus cras adipiscing enim eu turpis egestas. Dui faucibus in ornare quam viverra orci sagittis eu. Vivamus at augue eget arcu dictum. Magna fringilla urna porttitor rhoncus. Sollicitudin nibh sit amet commodo nulla facilisi.
      
      Vitae justo eget magna fermentum iaculis eu non diam. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Scelerisque eu ultrices vitae auctor eu augue ut lectus. In mollis nunc sed id semper risus in. Vitae sapien pellentesque habitant morbi. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. At risus viverra adipiscing at in tellus integer feugiat. Nibh tellus molestie nunc non blandit massa.`,
    author: 'Jane Doe',
  },
  {
    title: 'Blog Title 3',
    img:
      'https://images.unsplash.com/photo-1561469372-eb082b4f8f44?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8bWFjJTIwYXByb3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam etiam erat velit scelerisque. Praesent tristique magna sit amet purus gravida quis blandit. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Non odio euismod lacinia at quis. Mauris pellentesque pulvinar pellentesque habitant. Viverra accumsan in nisl nisi scelerisque. Risus feugiat in ante metus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum lacinia quis vel eros donec ac odio tempor.

      Sed elementum tempus egestas sed sed risus. Varius vel pharetra vel turpis nunc eget lorem. Diam vulputate ut pharetra sit amet. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Facilisis volutpat est velit egestas dui. Est ultricies integer quis auctor elit sed. Lacus sed viverra tellus in hac. Non blandit massa enim nec dui nunc mattis. Dolor sed viverra ipsum nunc. Fringilla urna porttitor rhoncus dolor purus. Vitae tempus quam pellentesque nec nam aliquam sem. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Duis convallis convallis tellus id interdum velit laoreet id donec. Mi bibendum neque egestas congue quisque egestas. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Aliquam ut porttitor leo a diam sollicitudin. Dui faucibus in ornare quam viverra orci sagittis.
      
      Nec ullamcorper sit amet risus nullam eget. Tortor consequat id porta nibh venenatis cras sed felis eget. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Consequat semper viverra nam libero justo laoreet. Augue eget arcu dictum varius duis. Tortor posuere ac ut consequat semper. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Condimentum lacinia quis vel eros donec ac odio tempor. Id diam vel quam elementum pulvinar etiam non quam.
      
      Nec ullamcorper sit amet risus. Enim lobortis scelerisque fermentum dui faucibus in ornare. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Sed nisi lacus sed viverra tellus in hac. Cras pulvinar mattis nunc sed. In hendrerit gravida rutrum quisque. Vulputate odio ut enim blandit volutpat maecenas. Sed odio morbi quis commodo. Tellus cras adipiscing enim eu turpis egestas. Dui faucibus in ornare quam viverra orci sagittis eu. Vivamus at augue eget arcu dictum. Magna fringilla urna porttitor rhoncus. Sollicitudin nibh sit amet commodo nulla facilisi.
      
      Vitae justo eget magna fermentum iaculis eu non diam. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Scelerisque eu ultrices vitae auctor eu augue ut lectus. In mollis nunc sed id semper risus in. Vitae sapien pellentesque habitant morbi. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. At risus viverra adipiscing at in tellus integer feugiat. Nibh tellus molestie nunc non blandit massa.`,
    author: 'Larry Smith',
  },
  {
    title: 'Blog Title 4',
    img:
      'https://images.unsplash.com/photo-1444464666168-49d633b86797?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjZ8fG5hdHVyZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam etiam erat velit scelerisque. Praesent tristique magna sit amet purus gravida quis blandit. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Non odio euismod lacinia at quis. Mauris pellentesque pulvinar pellentesque habitant. Viverra accumsan in nisl nisi scelerisque. Risus feugiat in ante metus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum lacinia quis vel eros donec ac odio tempor.

      Sed elementum tempus egestas sed sed risus. Varius vel pharetra vel turpis nunc eget lorem. Diam vulputate ut pharetra sit amet. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Facilisis volutpat est velit egestas dui. Est ultricies integer quis auctor elit sed. Lacus sed viverra tellus in hac. Non blandit massa enim nec dui nunc mattis. Dolor sed viverra ipsum nunc. Fringilla urna porttitor rhoncus dolor purus. Vitae tempus quam pellentesque nec nam aliquam sem. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Duis convallis convallis tellus id interdum velit laoreet id donec. Mi bibendum neque egestas congue quisque egestas. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Aliquam ut porttitor leo a diam sollicitudin. Dui faucibus in ornare quam viverra orci sagittis.
      
      Nec ullamcorper sit amet risus nullam eget. Tortor consequat id porta nibh venenatis cras sed felis eget. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Consequat semper viverra nam libero justo laoreet. Augue eget arcu dictum varius duis. Tortor posuere ac ut consequat semper. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Condimentum lacinia quis vel eros donec ac odio tempor. Id diam vel quam elementum pulvinar etiam non quam.
      
      Nec ullamcorper sit amet risus. Enim lobortis scelerisque fermentum dui faucibus in ornare. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Sed nisi lacus sed viverra tellus in hac. Cras pulvinar mattis nunc sed. In hendrerit gravida rutrum quisque. Vulputate odio ut enim blandit volutpat maecenas. Sed odio morbi quis commodo. Tellus cras adipiscing enim eu turpis egestas. Dui faucibus in ornare quam viverra orci sagittis eu. Vivamus at augue eget arcu dictum. Magna fringilla urna porttitor rhoncus. Sollicitudin nibh sit amet commodo nulla facilisi.
      
      Vitae justo eget magna fermentum iaculis eu non diam. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Scelerisque eu ultrices vitae auctor eu augue ut lectus. In mollis nunc sed id semper risus in. Vitae sapien pellentesque habitant morbi. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. At risus viverra adipiscing at in tellus integer feugiat. Nibh tellus molestie nunc non blandit massa.`,
    author: 'Josh',
  },
  {
    title: 'Blog Title 5',
    img:
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8c2hvZXN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam etiam erat velit scelerisque. Praesent tristique magna sit amet purus gravida quis blandit. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Non odio euismod lacinia at quis. Mauris pellentesque pulvinar pellentesque habitant. Viverra accumsan in nisl nisi scelerisque. Risus feugiat in ante metus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum lacinia quis vel eros donec ac odio tempor.

      Sed elementum tempus egestas sed sed risus. Varius vel pharetra vel turpis nunc eget lorem. Diam vulputate ut pharetra sit amet. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Facilisis volutpat est velit egestas dui. Est ultricies integer quis auctor elit sed. Lacus sed viverra tellus in hac. Non blandit massa enim nec dui nunc mattis. Dolor sed viverra ipsum nunc. Fringilla urna porttitor rhoncus dolor purus. Vitae tempus quam pellentesque nec nam aliquam sem. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Duis convallis convallis tellus id interdum velit laoreet id donec. Mi bibendum neque egestas congue quisque egestas. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Aliquam ut porttitor leo a diam sollicitudin. Dui faucibus in ornare quam viverra orci sagittis.
      
      Nec ullamcorper sit amet risus nullam eget. Tortor consequat id porta nibh venenatis cras sed felis eget. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Consequat semper viverra nam libero justo laoreet. Augue eget arcu dictum varius duis. Tortor posuere ac ut consequat semper. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Condimentum lacinia quis vel eros donec ac odio tempor. Id diam vel quam elementum pulvinar etiam non quam.
      
      Nec ullamcorper sit amet risus. Enim lobortis scelerisque fermentum dui faucibus in ornare. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Sed nisi lacus sed viverra tellus in hac. Cras pulvinar mattis nunc sed. In hendrerit gravida rutrum quisque. Vulputate odio ut enim blandit volutpat maecenas. Sed odio morbi quis commodo. Tellus cras adipiscing enim eu turpis egestas. Dui faucibus in ornare quam viverra orci sagittis eu. Vivamus at augue eget arcu dictum. Magna fringilla urna porttitor rhoncus. Sollicitudin nibh sit amet commodo nulla facilisi.
      
      Vitae justo eget magna fermentum iaculis eu non diam. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Scelerisque eu ultrices vitae auctor eu augue ut lectus. In mollis nunc sed id semper risus in. Vitae sapien pellentesque habitant morbi. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. At risus viverra adipiscing at in tellus integer feugiat. Nibh tellus molestie nunc non blandit massa.`,
    author: 'Jenny',
  },
  {
    title: 'Blog Title 6',
    img:
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8aGVhZHBob25lc3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam etiam erat velit scelerisque. Praesent tristique magna sit amet purus gravida quis blandit. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Non odio euismod lacinia at quis. Mauris pellentesque pulvinar pellentesque habitant. Viverra accumsan in nisl nisi scelerisque. Risus feugiat in ante metus. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum lacinia quis vel eros donec ac odio tempor.

      Sed elementum tempus egestas sed sed risus. Varius vel pharetra vel turpis nunc eget lorem. Diam vulputate ut pharetra sit amet. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Facilisis volutpat est velit egestas dui. Est ultricies integer quis auctor elit sed. Lacus sed viverra tellus in hac. Non blandit massa enim nec dui nunc mattis. Dolor sed viverra ipsum nunc. Fringilla urna porttitor rhoncus dolor purus. Vitae tempus quam pellentesque nec nam aliquam sem. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Duis convallis convallis tellus id interdum velit laoreet id donec. Mi bibendum neque egestas congue quisque egestas. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Aliquam ut porttitor leo a diam sollicitudin. Dui faucibus in ornare quam viverra orci sagittis.
      
      Nec ullamcorper sit amet risus nullam eget. Tortor consequat id porta nibh venenatis cras sed felis eget. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Consequat semper viverra nam libero justo laoreet. Augue eget arcu dictum varius duis. Tortor posuere ac ut consequat semper. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Condimentum lacinia quis vel eros donec ac odio tempor. Id diam vel quam elementum pulvinar etiam non quam.
      
      Nec ullamcorper sit amet risus. Enim lobortis scelerisque fermentum dui faucibus in ornare. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Sed nisi lacus sed viverra tellus in hac. Cras pulvinar mattis nunc sed. In hendrerit gravida rutrum quisque. Vulputate odio ut enim blandit volutpat maecenas. Sed odio morbi quis commodo. Tellus cras adipiscing enim eu turpis egestas. Dui faucibus in ornare quam viverra orci sagittis eu. Vivamus at augue eget arcu dictum. Magna fringilla urna porttitor rhoncus. Sollicitudin nibh sit amet commodo nulla facilisi.
      
      Vitae justo eget magna fermentum iaculis eu non diam. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Scelerisque eu ultrices vitae auctor eu augue ut lectus. In mollis nunc sed id semper risus in. Vitae sapien pellentesque habitant morbi. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. At risus viverra adipiscing at in tellus integer feugiat. Nibh tellus molestie nunc non blandit massa.`,
    author: 'Ravi',
  },
];

const seedDB = async () => {
  await Blog.insertMany(blogs);
  console.log('DB Seeded');
};

module.exports = seedDB;
